### ISSUE TITLE
should add `cert.generated: true` option to enable/disable cert generation

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-certs#23]
There is a case that we need a root CA generated only, not a certificate. So this option is introduced. It's enabled by default (to keep the same behavior as before), users can override to disable cert generation.

default:
```yaml
teracy-dev-certs:
 # cert_days: 200 # deprecate this
  cert:
    days: 200
    generated: true # enabled by default to generate a CA signed certificate
```

users can override:

```yaml
teracy-dev-certs:
  cert:
    generated: false # or 0, no
```

use https://github.com/teracyhq/dev/blob/develop/lib/teracy-dev/util.rb#L38 to check boolean value.
