### ISSUE TITLE
should add `ca.pkcs1_generated: false` to disable/enable the generation of PKCS#1 format

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-certs#27]
the CA key file is generated with PKCS#8 format, sometimes we need to generate and use PKCS#1 format instead (see https://github.com/teracyhq-incubator/teracy-dev-k8s/pull/60)

default:
```yaml
teracy-dev-certs:
  # ca_days: 2000 # deprecate this, use ca.days instead
  ca:
    days: 200
    pkcs1_generated: false # to generate the PKCS#1 *-ca.key from the *-ca-key.pem file
```

users can override:

```yaml
teracy-dev-certs:
  ca:
    pkcs1_generated: true # or 1, yes
```

use https://github.com/teracyhq/dev/blob/develop/lib/teracy-dev/util.rb#L38 to check boolean value.
