### ISSUE TITLE
should fix the cert days signed by the self signed root CA

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-certs#32]
from:

```yaml
    - name: Generate the {{ common_name }} certificate signed by the self-signed CA
      openssl_certificate:
        path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}.crt"
        csr_path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}.csr"
        ownca_path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}-ca.crt"
        ownca_privatekey_path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}-ca-key.pem"
        valid_in: "{{ cert_days*24*60*60 }}"  # seconds
        provider: ownca
      when: cert_generated
```

to

```yaml
    - name: Generate the {{ common_name }} certificate signed by the self-signed CA
      openssl_certificate:
        path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}.crt"
        csr_path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}.csr"
        ownca_path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}-ca.crt"
        ownca_privatekey_path: "{{ certs_path }}/{{ common_name | replace('.', '-') }}-ca-key.pem"
        ownca_not_after: "+{{ cert_days }}d"
        provider: ownca
      when: cert_generated
```

Set the default days is 825 days https://www.entrustdatacard.com/blog/2017/march/maximum-certificate-lifetime-drops-to-825-days-in-2018

now all browsers will not accept certs with more than 825 days.
